server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      password: pass
      name: user

jwt:
  secret: a5e486f3-313a-434f-9139-24aee910f95c
  TTLms: 0